print('+button == add, code == git add file name')
print('now staged changed')
print('if something changed, click add button')
print('version management is commit')
print('commit')
print('if something wrong click - button')
print('테스트2 다시한번 푸쉬')